import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/UI/card"
import { CheckCircle2 } from "lucide-react"

// Placeholder data for the rationale. In a real application, this would be
// dynamically generated by the AI based on the optimization results.
const rationalePoints = [
  "Train T-234 held for 2 mins to resolve conflict at Junction B.",
  "Train T-891 rerouted via northern corridor, adding 5 mins but avoiding maintenance delays.",
  "Network efficiency improved by 12% compared to baseline schedule.",
]

export default function Explanation() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Optimization Rationale</CardTitle>
        <CardDescription>
          The logic behind the recommended actions.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ul className="space-y-3">
          {rationalePoints.map((point, index) => (
            <li key={index} className="flex items-start">
              <CheckCircle2 className="h-5 w-5 text-green-400 mr-3 mt-0.5 flex-shrink-0" />
              <span className="text-sm text-muted-foreground">{point}</span>
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  )
}

